server:
  port: 8081

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: ${myDemoDatabase.datasource.driver-class-name}
    url: ${myDemoDatabase.datasource.url}
    username: ${myDemoDatabase.datasource.username}
    password: ${myDemoDatabase.datasource.password}

# ??mybatis
mybatis:
  #mapper????
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    # ??mybatis????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ??mybatis???????????  a_column = aColumn
    map-underscore-to-camel-case: true
